port control launch
tier4/autoware_launcher.iv.universe pull request #7
Opened 2020-11-06 15:10 UTC by TakaHoribe

## How to test

```
 ros2 launch control_launch control.launch.xml 
```

2020-11-18 13:24 UTC, esteve requested changes

2020-11-18 13:52 UTC, TakaHoribe commented on control_launch/package.xml
> +  <license>Apache 2.0</license>
Thanks, fixed.

2020-11-18 13:53 UTC, TakaHoribe commented on control_launch/config/mpc_follower/mpc_follower_param.yaml
> +/**:
What do you mean? I ported all param files in this package.

2020-11-18 15:11 UTC, esteve commented on control_launch/config/mpc_follower/mpc_follower_param.yaml
> +/**:
The params files are commented, they don't seem to be used anywhere.

2020-11-19 02:06 UTC, TakaHoribe commented on control_launch/config/mpc_follower/mpc_follower_param.yaml
> +/**:
Are you talking about the free-namespace `/**:` ? All parameters are loaded through the `control.launch.xml` and applied to each node. You can launch and check them.

2020-11-19 02:07 UTC, TakaHoribe commented on control_launch/config/mpc_follower/mpc_follower_param.yaml
> +/**:
```
 ros2 launch control_launch control.launch.xml 
```

2020-11-20 08:10 UTC, esteve approved these changes

2020-11-20 08:11 UTC, merged