Port planning launch
tier4/autoware_launcher.iv.universe pull request #9
Opened 2020-11-06 15:29 UTC by TakaHoribe

## How to run

```
ros2 launch planning_launch planning.launch.xml
```

 - [ ] scenario_selector
 - [ ] behavior_planning
 - [ ] motion_planning
 - [ ] freespace_planner
 - [ ] costmap_generator
 - [ ] scenario_selector
 - [ ] motion_velocity_optimizer

2020-11-25 11:23 UTC, mitsudome-r requested changes
There were few issues which I couldn't find the best way to fix.

* remapping of topics in included launch files are not allowed anymore. Instead, I think we should replace it by arguments to the launch files. However, this would require some modifications in Pilot.Auto as well.
* running `ros2 topic pub` in a launch file. I suggest using `executable` unless someone knows cleaner way to fix this.

2020-11-25 11:23 UTC, mitsudome-r commented on planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
>    <node pkg="rostopic" type="rostopic" name="auto_approve_lane_change" args="pub /planning/scenario_planning/lane_driving/lane_change_approval std_msgs/Bool 'data: true' -r 10" />
`rostopic` is not available in ros2.
I'm not sure if there are any good substitute, but I know we can replace it with `executable` to run it as a command.
```suggestion
  <executable cmd="ros2 topic pub /planning/scenario_planning/lane_driving/lane_change_approval std_msgs/msg/Bool 'data: true' -r 10"/>
```

2020-11-25 11:30 UTC, mitsudome-r commented
@TakaHoribe I have created PR to your branch with suggestions I made. Feel free to merge or use it as a reference to fix your launch file. https://github.com/TakaHoribe/autoware_launcher.iv.universe/pull/1/files

2020-11-25 12:13 UTC, TakaHoribe commented
@mitsudome-r Thank you! I merged your branch.

2020-11-25 12:40 UTC, mitsudome-r commented
@TakaHoribe Could you also review https://github.com/tier4/Pilot.Auto/pull/122 ?
This PR should be ready to be merged once the above PR is merged.

2020-11-25 12:49 UTC, TakaHoribe commented
@mitsudome-r sure. I'm testing now.

2020-11-26 03:50 UTC, mitsudome-r approved these changes

2020-11-26 03:50 UTC, merged